-- =============================================================================
-- NubixPlus - esquema base (PostgreSQL 14+)
-- Generado a partir de las entidades JPA de nubixplus-lib.
--
-- Orden de creacion (respeta las FK):
--   permissions -> organizations -> users -> roles -> role_permissions
--   -> user_organizations -> user_organization_roles -> refresh_tokens
--
-- Convenciones heredadas de las entidades:
--   * PK  : BIGINT IDENTITY (GenerationType.IDENTITY)
--   * LocalDateTime     -> TIMESTAMP(6) (sin zona horaria)
--   * @Enumerated(STRING) -> VARCHAR + CHECK
--   * BaseEntity        -> id, created_at, updated_at
--   * AuditableEntity   -> lo de BaseEntity mas created_by, updated_by,
--                          version (@Version) y deleted (borrado logico)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- permissions  (Permission extends AuditableEntity)
-- -----------------------------------------------------------------------------
CREATE TABLE permissions (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    code        VARCHAR(100) NOT NULL,            -- formato modulo:accion (users:create)
    name        VARCHAR(120) NOT NULL,
    description VARCHAR(300),
    module      VARCHAR(60)  NOT NULL,
    action      VARCHAR(60)  NOT NULL,
    -- AuditableEntity
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    created_by  VARCHAR(120),
    updated_by  VARCHAR(120),
    version     BIGINT       NOT NULL DEFAULT 0,
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_permissions          PRIMARY KEY (id),
    CONSTRAINT uk_permissions_code     UNIQUE (code)
);

CREATE INDEX ix_permissions_module ON permissions (module);

COMMENT ON TABLE  permissions      IS 'Permiso atomico del sistema, evaluado en @PreAuthorize';
COMMENT ON COLUMN permissions.code IS 'modulo:accion, ej. users:create';


-- -----------------------------------------------------------------------------
-- organizations  (Organization extends AuditableEntity) -- tenant
-- -----------------------------------------------------------------------------
CREATE TABLE organizations (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    legal_name      VARCHAR(200) NOT NULL,
    commercial_name VARCHAR(200),
    document_type   VARCHAR(20)  NOT NULL,
    document_number VARCHAR(20)  NOT NULL,        -- normalizado: solo digitos
    email           VARCHAR(150),
    phone           VARCHAR(30),
    address         VARCHAR(300),
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    timezone        VARCHAR(60)           DEFAULT 'America/Santo_Domingo',
    currency        VARCHAR(3)            DEFAULT 'DOP',
    logo_url        VARCHAR(500),
    -- AuditableEntity
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    created_by      VARCHAR(120),
    updated_by      VARCHAR(120),
    version         BIGINT       NOT NULL DEFAULT 0,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_organizations                     PRIMARY KEY (id),
    CONSTRAINT uk_organizations_document_number     UNIQUE (document_number),
    CONSTRAINT ck_organizations_document_type       CHECK (document_type IN ('RNC', 'CEDULA')),
    CONSTRAINT ck_organizations_status              CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

CREATE INDEX ix_organizations_status ON organizations (status);
-- ix_organizations_document_number del @Table es redundante: uk_organizations_document_number
-- ya crea el indice unico. Se omite a proposito.

COMMENT ON COLUMN organizations.document_number IS 'RNC (9 digitos) o cedula (11), solo digitos; viaja en X-Company-Document';


-- -----------------------------------------------------------------------------
-- users  (User extends AuditableEntity) -- identidad global, sin tenant
-- -----------------------------------------------------------------------------
CREATE TABLE users (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    email                 VARCHAR(180) NOT NULL,  -- siempre persistido en minusculas
    password_hash         VARCHAR(200) NOT NULL,
    first_name            VARCHAR(100) NOT NULL,
    last_name             VARCHAR(100) NOT NULL,
    phone                 VARCHAR(30),
    status                VARCHAR(30)  NOT NULL DEFAULT 'ACTIVE',
    email_verified        BOOLEAN      NOT NULL DEFAULT FALSE,
    must_change_password  BOOLEAN      NOT NULL DEFAULT FALSE,
    last_login_at         TIMESTAMP(6),
    password_changed_at   TIMESTAMP(6),
    failed_login_attempts INTEGER      NOT NULL DEFAULT 0,
    locked_until          TIMESTAMP(6),
    avatar_url            VARCHAR(500),
    locale                VARCHAR(10),
    -- AuditableEntity
    created_at            TIMESTAMP(6) NOT NULL,
    updated_at            TIMESTAMP(6) NOT NULL,
    created_by            VARCHAR(120),
    updated_by            VARCHAR(120),
    version               BIGINT       NOT NULL DEFAULT 0,
    deleted               BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_users        PRIMARY KEY (id),
    CONSTRAINT uk_users_email  UNIQUE (email),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'PENDING_ACTIVATION', 'INACTIVE', 'LOCKED', 'SUSPENDED'))
);

CREATE INDEX ix_users_status ON users (status);

-- RECOMENDADO: los repositorios buscan con lower(email) (findByEmailIgnoreCase...,
-- y el fetch join del login). El indice unico plano NO se usa en esas consultas.
CREATE UNIQUE INDEX ux_users_email_lower ON users (lower(email));


-- -----------------------------------------------------------------------------
-- roles  (Role extends AuditableEntity)
--   organization_id NULL = rol de sistema, visible para todas las organizaciones
-- -----------------------------------------------------------------------------
CREATE TABLE roles (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    code            VARCHAR(60)  NOT NULL,        -- MAYUSCULAS, ej. ORG_ADMIN
    name            VARCHAR(120) NOT NULL,
    description     VARCHAR(300),
    organization_id BIGINT,                       -- NULL => rol de sistema
    system_role     BOOLEAN      NOT NULL DEFAULT FALSE,
    -- AuditableEntity
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    created_by      VARCHAR(120),
    updated_by      VARCHAR(120),
    version         BIGINT       NOT NULL DEFAULT 0,
    deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_roles                    PRIMARY KEY (id),
    CONSTRAINT uk_roles_organization_code  UNIQUE (organization_id, code),
    CONSTRAINT fk_roles_organization       FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE INDEX ix_roles_code         ON roles (code);
CREATE INDEX ix_roles_organization ON roles (organization_id);

-- RECOMENDADO: uk_roles_organization_code NO protege los roles de sistema, porque
-- en SQL dos filas con organization_id NULL nunca chocan. Este indice parcial si.
CREATE UNIQUE INDEX ux_roles_code_global ON roles (code) WHERE organization_id IS NULL;


-- -----------------------------------------------------------------------------
-- role_permissions  (@ManyToMany Role <-> Permission)
-- -----------------------------------------------------------------------------
CREATE TABLE role_permissions (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT pk_role_permissions            PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role       FOREIGN KEY (role_id)       REFERENCES roles (id)       ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions (id)
);

-- La PK ya indexa role_id; hace falta el indice inverso para "que roles usan este permiso".
CREATE INDEX ix_role_permissions_permission ON role_permissions (permission_id);


-- -----------------------------------------------------------------------------
-- user_organizations  (UserOrganization extends AuditableEntity) -- membresia
-- -----------------------------------------------------------------------------
CREATE TABLE user_organizations (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    user_id         BIGINT      NOT NULL,
    organization_id BIGINT      NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    is_default      BOOLEAN     NOT NULL DEFAULT FALSE,
    joined_at       TIMESTAMP(6),
    job_title       VARCHAR(120),
    -- AuditableEntity
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    created_by      VARCHAR(120),
    updated_by      VARCHAR(120),
    version         BIGINT      NOT NULL DEFAULT 0,
    deleted         BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_user_organizations                 PRIMARY KEY (id),
    CONSTRAINT uk_user_organizations_user_org        UNIQUE (user_id, organization_id),
    CONSTRAINT fk_user_organizations_user            FOREIGN KEY (user_id)         REFERENCES users (id),
    CONSTRAINT fk_user_organizations_organization    FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT ck_user_organizations_status          CHECK (status IN ('ACTIVE', 'PENDING', 'INACTIVE', 'REVOKED'))
);

CREATE INDEX ix_user_organizations_organization ON user_organizations (organization_id);
-- ix_user_organizations_user es redundante: uk_user_organizations_user_org ya
-- indexa user_id como columna lider. Se omite a proposito.

-- RECOMENDADO: una sola organizacion por defecto por usuario.
CREATE UNIQUE INDEX ux_user_organizations_default
    ON user_organizations (user_id)
    WHERE is_default AND deleted = FALSE;


-- -----------------------------------------------------------------------------
-- user_organization_roles  (@ManyToMany UserOrganization <-> Role)
-- -----------------------------------------------------------------------------
CREATE TABLE user_organization_roles (
    user_organization_id BIGINT NOT NULL,
    role_id              BIGINT NOT NULL,
    CONSTRAINT pk_user_organization_roles          PRIMARY KEY (user_organization_id, role_id),
    CONSTRAINT fk_user_organization_roles_member   FOREIGN KEY (user_organization_id) REFERENCES user_organizations (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_organization_roles_role     FOREIGN KEY (role_id)              REFERENCES roles (id)
);

CREATE INDEX ix_user_organization_roles_role ON user_organization_roles (role_id);


-- -----------------------------------------------------------------------------
-- refresh_tokens  (RefreshToken extends BaseEntity -> sin auditoria ni version)
-- -----------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    token_hash      VARCHAR(128) NOT NULL,        -- hash, nunca el token en claro
    user_id         BIGINT       NOT NULL,
    organization_id BIGINT       NOT NULL,
    issued_at       TIMESTAMP(6) NOT NULL,
    expires_at      TIMESTAMP(6) NOT NULL,
    revoked         BOOLEAN      NOT NULL DEFAULT FALSE,
    revoked_at      TIMESTAMP(6),
    user_agent      VARCHAR(300),
    ip_address      VARCHAR(60),
    -- BaseEntity
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_refresh_tokens                 PRIMARY KEY (id),
    CONSTRAINT uk_refresh_tokens_hash            UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user            FOREIGN KEY (user_id)         REFERENCES users (id)         ON DELETE CASCADE,
    CONSTRAINT fk_refresh_tokens_organization    FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE INDEX ix_refresh_tokens_expires_at ON refresh_tokens (expires_at);

-- ix_refresh_tokens_user del @Table se reemplaza por este compuesto: revokeAllForUserAndOrganization
-- filtra por user_id + organization_id + revoked.
CREATE INDEX ix_refresh_tokens_user_org ON refresh_tokens (user_id, organization_id);