-- =============================================================================
-- NubixPlus - esquema base (PostgreSQL 14+)
-- Generado a partir de las entidades JPA de nubixplus-lib.
--
-- Orden de creacion (respeta las FK):
--   permissions -> organizations -> users -> roles -> role_permissions
--   -> user_organizations -> user_organization_roles -> refresh_tokens
--   -> families -> categories -> products -> suppliers -> product_suppliers
--
-- Toda relacion N:M se modela con TRES tablas y una entidad intermedia propia
-- (role_permissions, user_organization_roles, product_suppliers). No hay
-- @ManyToMany en el modelo: nada de la N:M queda escondido detras del ORM.
--
-- Convenciones heredadas de las entidades:
--   * PK  : BIGINT IDENTITY (GenerationType.IDENTITY)
--   * LocalDateTime     -> TIMESTAMP(6) (sin zona horaria)
--   * @Enumerated(STRING) -> VARCHAR + CHECK
--   * BaseEntity        -> id, created_at, updated_at
--   * AuditableEntity   -> lo de BaseEntity mas created_by, updated_by,
--                          version (@Version)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- permissions  (Permission extends AuditableEntity)
-- -----------------------------------------------------------------------------
CREATE TABLE permissions (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    code        VARCHAR(100) NOT NULL,            -- formato modulo:accion (users:create)
    name        VARCHAR(120) NOT NULL,
    description VARCHAR(300),
    module      VARCHAR(60)  NOT NULL,
    action      VARCHAR(60)  NOT NULL,
    -- AuditableEntity
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    created_by  VARCHAR(120),
    updated_by  VARCHAR(120),
    version     BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_permissions          PRIMARY KEY (id),
    CONSTRAINT uk_permissions_code     UNIQUE (code)
);

CREATE INDEX ix_permissions_module ON permissions (module);

COMMENT ON TABLE  permissions      IS 'Permiso atomico del sistema, evaluado en @PreAuthorize';
COMMENT ON COLUMN permissions.code IS 'modulo:accion, ej. users:create';


-- -----------------------------------------------------------------------------
-- organizations  (Organization extends AuditableEntity) -- tenant
-- -----------------------------------------------------------------------------
CREATE TABLE organizations (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    legal_name      VARCHAR(200) NOT NULL,
    commercial_name VARCHAR(200),
    document_type   VARCHAR(20)  NOT NULL,
    document_number VARCHAR(20)  NOT NULL,        -- normalizado: solo digitos
    email           VARCHAR(150),
    phone           VARCHAR(30),
    address         VARCHAR(300),
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    timezone        VARCHAR(60)           DEFAULT 'America/Santo_Domingo',
    currency        VARCHAR(3)            DEFAULT 'DOP',
    logo_url        VARCHAR(500),
    -- AuditableEntity
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    created_by      VARCHAR(120),
    updated_by      VARCHAR(120),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_organizations                     PRIMARY KEY (id),
    CONSTRAINT uk_organizations_document_number     UNIQUE (document_number),
    CONSTRAINT ck_organizations_document_type       CHECK (document_type IN ('RNC', 'CEDULA'))
);

-- La disponibilidad es binaria: boolean, no un enum de dos valores con su CHECK.
CREATE INDEX ix_organizations_active ON organizations (active);
-- ix_organizations_document_number del @Table es redundante: uk_organizations_document_number
-- ya crea el indice unico. Se omite a proposito.

COMMENT ON COLUMN organizations.document_number IS 'RNC (9 digitos) o cedula (11), solo digitos; viaja en X-Company-Document';


-- -----------------------------------------------------------------------------
-- users  (User extends AuditableEntity) -- identidad global, sin tenant
-- -----------------------------------------------------------------------------
CREATE TABLE users (
    id                    BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    email                 VARCHAR(180) NOT NULL,  -- siempre persistido en minusculas
    password_hash         VARCHAR(200) NOT NULL,
    first_name            VARCHAR(100) NOT NULL,
    last_name             VARCHAR(100) NOT NULL,
    phone                 VARCHAR(30),
    status                VARCHAR(30)  NOT NULL DEFAULT 'ACTIVE',
    email_verified        BOOLEAN      NOT NULL DEFAULT FALSE,
    must_change_password  BOOLEAN      NOT NULL DEFAULT FALSE,
    last_login_at         TIMESTAMP(6),
    password_changed_at   TIMESTAMP(6),
    failed_login_attempts INTEGER      NOT NULL DEFAULT 0,
    locked_until          TIMESTAMP(6),
    avatar_url            VARCHAR(500),
    locale                VARCHAR(10),
    -- AuditableEntity
    created_at            TIMESTAMP(6) NOT NULL,
    updated_at            TIMESTAMP(6) NOT NULL,
    created_by            VARCHAR(120),
    updated_by            VARCHAR(120),
    version               BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_users        PRIMARY KEY (id),
    CONSTRAINT uk_users_email  UNIQUE (email),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'PENDING_ACTIVATION', 'INACTIVE', 'LOCKED', 'SUSPENDED'))
);

CREATE INDEX ix_users_status ON users (status);

-- RECOMENDADO: los repositorios buscan con lower(email) (findByEmailIgnoreCase...,
-- y el fetch join del login). El indice unico plano NO se usa en esas consultas.
CREATE UNIQUE INDEX ux_users_email_lower ON users (lower(email));


-- -----------------------------------------------------------------------------
-- roles  (Role extends AuditableEntity)
--   organization_id NULL = rol de sistema, visible para todas las organizaciones
-- -----------------------------------------------------------------------------
CREATE TABLE roles (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    code            VARCHAR(60)  NOT NULL,        -- MAYUSCULAS, ej. ORG_ADMIN
    name            VARCHAR(120) NOT NULL,
    description     VARCHAR(300),
    organization_id BIGINT,                       -- NULL => rol de sistema
    system_role     BOOLEAN      NOT NULL DEFAULT FALSE,
    -- AuditableEntity
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    created_by      VARCHAR(120),
    updated_by      VARCHAR(120),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_roles                    PRIMARY KEY (id),
    CONSTRAINT uk_roles_organization_code  UNIQUE (organization_id, code),
    CONSTRAINT fk_roles_organization       FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE INDEX ix_roles_code         ON roles (code);
CREATE INDEX ix_roles_organization ON roles (organization_id);

-- RECOMENDADO: uk_roles_organization_code NO protege los roles de sistema, porque
-- en SQL dos filas con organization_id NULL nunca chocan. Este indice parcial si.
CREATE UNIQUE INDEX ux_roles_code_global ON roles (code) WHERE organization_id IS NULL;


-- -----------------------------------------------------------------------------
-- role_permissions  (RolePermission: tabla intermedia EXPLICITA Role <-> Permission)
--
-- La relacion N:M no la resuelve el ORM: la fila del medio es una entidad
-- (RolePermission extends BaseEntity), con su propio id y sus fechas. La unicidad
-- del par la garantiza uk_role_permissions, no la PK.
-- -----------------------------------------------------------------------------
CREATE TABLE role_permissions (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    role_id       BIGINT       NOT NULL,
    permission_id BIGINT       NOT NULL,
    -- BaseEntity (sin auditoria: un vinculo se otorga o se revoca)
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_role_permissions            PRIMARY KEY (id),
    CONSTRAINT uk_role_permissions            UNIQUE (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role       FOREIGN KEY (role_id)       REFERENCES roles (id)       ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions (id)
);

-- uk_role_permissions ya indexa role_id como columna lider, asi que ix_role_permissions_role
-- del @Table es redundante y se omite a proposito. El inverso si hace falta, para
-- responder "que roles usan este permiso".
CREATE INDEX ix_role_permissions_permission ON role_permissions (permission_id);


-- -----------------------------------------------------------------------------
-- user_organizations  (UserOrganization extends AuditableEntity) -- membresia
-- -----------------------------------------------------------------------------
CREATE TABLE user_organizations (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    user_id         BIGINT      NOT NULL,
    organization_id BIGINT      NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    default_organization BOOLEAN NOT NULL DEFAULT FALSE,
    joined_at       TIMESTAMP(6),
    job_title       VARCHAR(120),
    -- AuditableEntity
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    created_by      VARCHAR(120),
    updated_by      VARCHAR(120),
    version         BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_user_organizations                 PRIMARY KEY (id),
    CONSTRAINT uk_user_organizations_user_org        UNIQUE (user_id, organization_id),
    CONSTRAINT fk_user_organizations_user            FOREIGN KEY (user_id)         REFERENCES users (id),
    CONSTRAINT fk_user_organizations_organization    FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT ck_user_organizations_status          CHECK (status IN ('ACTIVE', 'PENDING', 'INACTIVE', 'REVOKED'))
);

CREATE INDEX ix_user_organizations_organization ON user_organizations (organization_id);
-- ix_user_organizations_user es redundante: uk_user_organizations_user_org ya
-- indexa user_id como columna lider. Se omite a proposito.

-- RECOMENDADO: una sola organizacion por defecto por usuario.
CREATE UNIQUE INDEX ux_user_organizations_default
    ON user_organizations (user_id)
    WHERE default_organization;


-- -----------------------------------------------------------------------------
-- user_organization_roles  (UserOrganizationRole: tabla intermedia EXPLICITA
--                           UserOrganization <-> Role)
-- -----------------------------------------------------------------------------
CREATE TABLE user_organization_roles (
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_organization_id BIGINT       NOT NULL,
    role_id              BIGINT       NOT NULL,
    -- BaseEntity
    created_at           TIMESTAMP(6) NOT NULL,
    updated_at           TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_user_organization_roles        PRIMARY KEY (id),
    CONSTRAINT uk_user_organization_roles        UNIQUE (user_organization_id, role_id),
    CONSTRAINT fk_user_organization_roles_member FOREIGN KEY (user_organization_id) REFERENCES user_organizations (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_organization_roles_role   FOREIGN KEY (role_id)              REFERENCES roles (id)
);

-- ix_user_organization_roles_member es redundante (uk_user_organization_roles ya
-- indexa la columna lider). Se omite a proposito.
CREATE INDEX ix_user_organization_roles_role ON user_organization_roles (role_id);


-- -----------------------------------------------------------------------------
-- refresh_tokens  (RefreshToken extends BaseEntity -> sin auditoria ni version)
-- -----------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    token_hash      VARCHAR(128) NOT NULL,        -- hash, nunca el token en claro
    user_id         BIGINT       NOT NULL,
    organization_id BIGINT       NOT NULL,
    issued_at       TIMESTAMP(6) NOT NULL,
    expires_at      TIMESTAMP(6) NOT NULL,
    revoked         BOOLEAN      NOT NULL DEFAULT FALSE,
    revoked_at      TIMESTAMP(6),
    user_agent      VARCHAR(300),
    ip_address      VARCHAR(60),
    -- BaseEntity
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_refresh_tokens                 PRIMARY KEY (id),
    CONSTRAINT uk_refresh_tokens_hash            UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user            FOREIGN KEY (user_id)         REFERENCES users (id)         ON DELETE CASCADE,
    CONSTRAINT fk_refresh_tokens_organization    FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE INDEX ix_refresh_tokens_expires_at ON refresh_tokens (expires_at);

-- ix_refresh_tokens_user del @Table se reemplaza por este compuesto: revokeAllForUserAndOrganization
-- filtra por user_id + organization_id + revoked.
CREATE INDEX ix_refresh_tokens_user_org ON refresh_tokens (user_id, organization_id);

-- =============================================================================
-- MODULO DE INVENTARIO
--
-- Jerarquia:               families 1:N categories 1:N products
-- Codigos del producto:    products 1:N product_codes
-- Relacion N:M del modulo: products 1:N product_suppliers N:1 suppliers
--
-- Todo el catalogo es POR COMPANIA: los codigos (code de familia/categoria/suplidor,
-- los product_codes y el documento del suplidor) son unicos dentro de la
-- organizacion y no en toda la plataforma. Dos companias pueden vender el mismo
-- articulo y comprarle al mismo proveedor.
--
-- Estados: la disponibilidad binaria va como boolean 'active'; solo products
-- conserva un enum 'status' porque tiene tres estados con comportamiento distinto.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- families  (Family extends AuditableEntity) -- nivel alto de la clasificacion
-- -----------------------------------------------------------------------------
CREATE TABLE families (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    code            VARCHAR(30)  NOT NULL,        -- MAYUSCULAS, ej. BEB
    name            VARCHAR(120) NOT NULL,
    description     VARCHAR(300),
    organization_id BIGINT       NOT NULL,
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    -- AuditableEntity
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    created_by      VARCHAR(120),
    updated_by      VARCHAR(120),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_families                   PRIMARY KEY (id),
    CONSTRAINT uk_families_organization_code UNIQUE (organization_id, code),
    CONSTRAINT fk_families_organization      FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

-- ix_families_organization es redundante: uk_families_organization_code ya indexa
-- organization_id como columna lider. Se omite a proposito.
CREATE INDEX ix_families_code   ON families (code);
CREATE INDEX ix_families_active ON families (active);

COMMENT ON TABLE families IS 'Familia: nivel superior de la clasificacion del catalogo';


-- -----------------------------------------------------------------------------
-- categories  (Category extends AuditableEntity) -- siempre bajo una familia
-- -----------------------------------------------------------------------------
CREATE TABLE categories (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    code            VARCHAR(30)  NOT NULL,        -- MAYUSCULAS, ej. REF
    name            VARCHAR(120) NOT NULL,
    description     VARCHAR(300),
    family_id       BIGINT       NOT NULL,        -- N:1, obligatorio
    organization_id BIGINT       NOT NULL,
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    -- AuditableEntity
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    created_by      VARCHAR(120),
    updated_by      VARCHAR(120),
    version         BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_categories                   PRIMARY KEY (id),
    CONSTRAINT uk_categories_organization_code UNIQUE (organization_id, code),
    CONSTRAINT fk_categories_family            FOREIGN KEY (family_id)       REFERENCES families (id),
    CONSTRAINT fk_categories_organization      FOREIGN KEY (organization_id) REFERENCES organizations (id)
);

CREATE INDEX ix_categories_family ON categories (family_id);
CREATE INDEX ix_categories_code   ON categories (code);
CREATE INDEX ix_categories_active ON categories (active);


-- -----------------------------------------------------------------------------
-- suppliers  (Supplier extends AuditableEntity)
--   document_number normalizado (solo digitos), igual que en organizations
-- -----------------------------------------------------------------------------
CREATE TABLE suppliers (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    code               VARCHAR(30)  NOT NULL,     -- MAYUSCULAS, ej. SUP-001
    legal_name         VARCHAR(200) NOT NULL,
    commercial_name    VARCHAR(200),
    document_type      VARCHAR(20),
    document_number    VARCHAR(20),
    email              VARCHAR(150),
    phone              VARCHAR(30),
    address            VARCHAR(300),
    contact_name       VARCHAR(150),
    payment_terms_days INTEGER,
    organization_id    BIGINT       NOT NULL,
    active             BOOLEAN      NOT NULL DEFAULT TRUE,
    -- AuditableEntity
    created_at         TIMESTAMP(6) NOT NULL,
    updated_at         TIMESTAMP(6) NOT NULL,
    created_by         VARCHAR(120),
    updated_by         VARCHAR(120),
    version            BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT pk_suppliers                       PRIMARY KEY (id),
    CONSTRAINT uk_suppliers_organization_code     UNIQUE (organization_id, code),
    CONSTRAINT uk_suppliers_organization_document UNIQUE (organization_id, document_number),
    CONSTRAINT fk_suppliers_organization          FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT ck_suppliers_document_type         CHECK (document_type IS NULL OR document_type IN ('RNC', 'CEDULA'))
);

CREATE INDEX ix_suppliers_document_number ON suppliers (document_number);
CREATE INDEX ix_suppliers_active          ON suppliers (active);

COMMENT ON COLUMN suppliers.document_number IS 'RNC o cedula, solo digitos; NULL cuando el suplidor no lo tiene registrado';


-- -----------------------------------------------------------------------------
-- products  (Product extends AuditableEntity)
--
-- El producto NO guarda sus codigos: viven en product_codes, uno por fila. Un
-- articulo acumula codigos de distinto tipo (SKU interno, UPC del fabricante, EAN
-- de la caja) y con columnas fijas cada tipo nuevo seria una migracion.
-- -----------------------------------------------------------------------------
CREATE TABLE products (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(200)  NOT NULL,
    description     VARCHAR(500),
    brand           VARCHAR(120),
    category_id     BIGINT        NOT NULL,
    organization_id BIGINT        NOT NULL,
    unit            VARCHAR(20)   NOT NULL DEFAULT 'UNIT',
    cost            NUMERIC(19,4),
    price           NUMERIC(19,4),
    track_stock     BOOLEAN       NOT NULL DEFAULT TRUE,
    min_stock       NUMERIC(19,4),
    max_stock       NUMERIC(19,4),
    status          VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    -- AuditableEntity
    created_at      TIMESTAMP(6)  NOT NULL,
    updated_at      TIMESTAMP(6)  NOT NULL,
    created_by      VARCHAR(120),
    updated_by      VARCHAR(120),
    version         BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT pk_products              PRIMARY KEY (id),
    CONSTRAINT fk_products_category     FOREIGN KEY (category_id)     REFERENCES categories (id),
    CONSTRAINT fk_products_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    -- status tiene tres estados con comportamiento distinto (DISCONTINUED no se
    -- vuelve a comprar pero se agota la existencia), por eso sigue siendo enum y no
    -- un boolean como el resto del catalogo.
    CONSTRAINT ck_products_status       CHECK (status IN ('ACTIVE', 'INACTIVE', 'DISCONTINUED')),
    CONSTRAINT ck_products_unit         CHECK (unit IN ('UNIT', 'PACK', 'BOX', 'DOZEN', 'GRAM', 'KILOGRAM',
                                                        'POUND', 'MILLILITER', 'LITER', 'GALLON', 'METER', 'FOOT'))
);

CREATE INDEX ix_products_organization ON products (organization_id);
CREATE INDEX ix_products_category     ON products (category_id);
CREATE INDEX ix_products_name         ON products (name);
CREATE INDEX ix_products_status       ON products (status);


-- -----------------------------------------------------------------------------
-- product_codes  (ProductCode extends BaseEntity)
--
--   PRODUCT 1 ── N PRODUCT_CODE     SKU / UPC12 / EAN13 / ...
--
-- Unicidad (organization_id, type, code_value):
--   * por compania y no global, porque el catalogo es de cada tenant y dos
--     companias pueden registrar el mismo EAN;
--   * tipo + valor y no solo valor, porque cada tipo es un espacio de nombres
--     distinto: un SKU interno '123456' y un CUSTOM '123456' son identificadores de
--     sistemas diferentes. Dentro de un mismo tipo si seria un duplicado real.
--
-- El valor va como texto: un EAN puede empezar en cero y ese cero es parte del
-- codigo. La columna se llama code_value porque VALUE es palabra reservada en H2.
-- -----------------------------------------------------------------------------
CREATE TABLE product_codes (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    product_id      BIGINT       NOT NULL,
    organization_id BIGINT       NOT NULL,       -- desnormalizado: lidera la unicidad
    type            VARCHAR(20)  NOT NULL,
    code_value      VARCHAR(60)  NOT NULL,
    -- BaseEntity (un codigo se agrega o se quita; sin auditoria)
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_product_codes                       PRIMARY KEY (id),
    CONSTRAINT uk_product_codes_organization_type_value UNIQUE (organization_id, type, code_value),
    CONSTRAINT fk_product_codes_product               FOREIGN KEY (product_id)      REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT fk_product_codes_organization          FOREIGN KEY (organization_id) REFERENCES organizations (id),
    CONSTRAINT ck_product_codes_type                  CHECK (type IN ('EAN8', 'EAN13', 'EAN14', 'UPC12', 'UPC6', 'SKU', 'CUSTOM'))
);

CREATE INDEX ix_product_codes_product ON product_codes (product_id);
CREATE INDEX ix_product_codes_value   ON product_codes (code_value);
CREATE INDEX ix_product_codes_type    ON product_codes (type);

COMMENT ON COLUMN product_codes.code_value IS 'Codigo ya normalizado: solo digitos en los GTIN, MAYUSCULAS en SKU y CUSTOM';


-- -----------------------------------------------------------------------------
-- product_suppliers  (ProductSupplier: tabla intermedia EXPLICITA
--                     Product <-> Supplier)
--
-- Ademas del vinculo guarda las condiciones pactadas con ese suplidor para ESE
-- producto, que es informacion que no cabe ni en products ni en suppliers.
-- -----------------------------------------------------------------------------
CREATE TABLE product_suppliers (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    product_id     BIGINT       NOT NULL,
    supplier_id    BIGINT       NOT NULL,
    supplier_reference   VARCHAR(60),                   -- referencia en el catalogo del suplidor
    last_cost      NUMERIC(19,4),
    lead_time_days INTEGER,
    preferred      BOOLEAN      NOT NULL DEFAULT FALSE,
    -- BaseEntity
    created_at     TIMESTAMP(6) NOT NULL,
    updated_at     TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_product_suppliers          PRIMARY KEY (id),
    CONSTRAINT uk_product_suppliers          UNIQUE (product_id, supplier_id),
    CONSTRAINT fk_product_suppliers_product  FOREIGN KEY (product_id)  REFERENCES products (id)  ON DELETE CASCADE,
    CONSTRAINT fk_product_suppliers_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers (id)
);

-- ix_product_suppliers_product es redundante (uk_product_suppliers ya indexa la
-- columna lider). Se omite a proposito.
CREATE INDEX ix_product_suppliers_supplier ON product_suppliers (supplier_id);

-- RECOMENDADO: un solo suplidor preferido por producto.
CREATE UNIQUE INDEX ux_product_suppliers_preferred
    ON product_suppliers (product_id)
    WHERE preferred;
